name: Sentry Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
      
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: yarn install

    - name: Build and deploy subgraph
      run: yarn build

    - name: Set version
      id: set-version
      run: echo "version=v$(cat package.json | jq -r .version)-$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

    - name: Create Sentry release
      uses: getsentry/action-release@v1.3.1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production
        version: ${{ steps.set-version.outputs.version }}
        sourcemaps: ./dist

